### ISSUE TITLE
Show only 100 results of search

### ISSUE THREAD

**Issue by omulverde** [Acer54/Webradio_v2#49]
Why is showing only 100 result? most of search finish at "b" or "c" caracter. Where are the rest?

**Comment by Acer54** [comment]
The "max results" are limited to 30 in this [code-line](https://github.com/Acer54/Webradio_v2/blob/244157767d0e8e3d8b77cdc67c760559f848140a/opt/webradio/ui/database_searcher.py#L527). It was limited because of the time which it takes for a higher result count. The youtube-player was intended to supplement own Music-Libraries... not as a single use music-box. 
If you need more searchresults, feel free to change it in your installation, but expect a higher process time.
Also the API from youtube will limit the search-results to a specific count... according to [this](https://developers.google.com/youtube/v3/docs/search/list#maxResults) the max count which the API can provide is 50.

Regards, 
Matthias
